---
version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    allow:
      # Allow only updates for dev dependencies
      - dependency-type: development
    open-pull-requests-limit: 3
