---
default_install_hook_types: [pre-commit]
exclude: |
  (?x)^(
                outputs/|
                wandb/|
                multirun/|
                dev/|
                data/|
                dev/|
                checkpoints/|
                notebooks/|
                .pre-commit-config.yaml
  )$

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --preview, --select=ALL, --fixable=ALL, --exclude=outputs/, --extend-ignore=TD003, --extend-ignore=FIX002, --extend-ignore=CPY001, --extend-ignore=S101, --exclude=dev/, --exclude=checkpoints/, --exclude=notebooks/, --exclude=run_scripts/, --exclude=scripts/, --exclude=multirun/, --exclude=wandb/, --exclude=data/
        ]
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.17.0
    hooks:
      - id: yamlfix
        entry: env YAMLFIX_LINE_LENGTH=88 yamlfix
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
    - id: yamllint
      name: yamllint
      args: ["--config-data={extends: default, rules: {line-length: {max: 100}}}"] 
      description: This hook runs yamllint.
      entry: yamllint
      language: python
      types: [file, yaml]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
    - id: shfmt 
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    - id: gitlint
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
    - id: shfmt 
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-builtin-literals
        args:
        - --no-allow-dict-kwargs
      - id: check-docstring-first
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: detect-aws-credentials
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --incremental --show-traceback
        language: system
        types: [file, python]
        stages: [pre-commit, manual]  
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        types: [python]
        stages: [pre-commit, manual] 
        pass_filenames: false
        args: [--warnings]
        additional_dependencies: ["pyright@1.1.390"]  
  
      

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [mypy]
  submodules: false
